#A christmas tree
print("          /*\            ")
print("         /***\          ")
print("        /*****\           ")
print("       /*******\          ")
print("      /*********\           ")
print("     /***********\         ")
print("    /*************\         ")
print("    ---------------")
print("           ||               ")
print("           ||               ")
print("           ||               ")
print("           ||               ")
print("    --------------------")